### ISSUE TITLE
error from seed-repo

### ISSUE THREAD

**Issue by bacongobbler** [deis/demo-charts#9]
```
11:00:44 /usr/local/bundle/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/deis/demo-charts/labels: 404 - Not Found // See: https://developer.github.com/v3/issues/labels/#create-a-label (Octokit::NotFound)
11:00:44    from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
11:00:44    from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
11:00:44    from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
11:00:44    from /usr/local/bundle/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
11:00:44    from /usr/local/bundle/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
11:00:44    from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
11:00:44    from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
11:00:44    from /usr/local/bundle/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
11:00:44    from /usr/local/bundle/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
11:00:44    from /usr/local/bundle/gems/octokit-4.2.0/lib/octokit/connection.rb:154:in `request'
11:00:44    from /usr/local/bundle/gems/octokit-4.2.0/lib/octokit/connection.rb:28:in `post'
11:00:44    from /usr/local/bundle/gems/octokit-4.2.0/lib/octokit/client/labels.rb:44:in `add_label'
11:00:44    from ./seed-repo:139:in `rescue in block in <main>'
11:00:44    from ./seed-repo:135:in `block in <main>'
11:00:44    from ./seed-repo:134:in `each'
11:00:44    from ./seed-repo:134:in `<main>'
11:00:44 Repository 'deis/demo-charts' exists. Skipping creation...
```

@rimusz would you mind updating the repo permissions so that it follows the same permissions on our other projects so Jenkins can update the labels, or [exempt it from seed-repo](https://github.com/deis/seed-repo/blob/master/list-repos#L23)? Thanks!

**Comment by rimusz** [comment]
@bacongobbler I did update the repo permissions
